### ISSUE TITLE
DevTools fails when nuxt-socket-io installed

### ISSUE THREAD

**Issue by de-soul** [nuxt/devtools#77] opened 2023-02-16 15:00 UTC
This happens, because both packages injects $nuxtSocket to the context. So, how to use DevTools with nuxt-socket-io in same application?

**Comment by antfu** [comment] 2023-02-16 22:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-16 22:21 UTC
