### ISSUE TITLE
fix: the "Runtime Config" tab has unreadable text in dark mode

### ISSUE THREAD

**Issue by stefanobartoletti** [nuxt/devtools#529] opened 2023-11-29 13:24 UTC
### 🐛 The bug

I don't know if this happens just to me, I think that devtools does not inherit styles from nuxt.

When I use dark mode some of the text inside the "Runtime Configs" is still dark, and not very readable

![Screenshot_20231129_125918](https://github.com/nuxt/devtools/assets/36746429/0c741cc4-1aff-43f1-909b-c074e0448d97)

### 🛠️ To reproduce

Use devtools in dark mode

### 🌈 Expected behavior

Text should have proper contrast

**Comment by stefanobartoletti** [comment] 2023-12-11 11:40
There is not much to reproduce I'm afraid, it happens just after starting a new project with `npx nuxi init` (using `pnpm` as package manager), without doing anything else.

I'm on Linux and tested this both on Firefox and Brave, if this is helpful

**Comment by antfu** [comment] 2024-01-11 16:21
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-11 16:21 UTC
Labels: bug
