### ISSUE TITLE
fix: component inspector doesn't behave as expected

### ISSUE THREAD

**Issue by Menna-elgallad** [nuxt/devtools#398] opened 2023-08-20 15:08 UTC
### 🐛 The bug

[screencast-localhost_3000-2023.08.20-17_16_53.webm](https://github.com/nuxt/devtools/assets/103152183/045a905b-5ee8-4fa1-b41b-4085dbd2197d) 

>    node  : v18.12.0 , 
Nuxt 3.6.5 , 
 "@nuxt/devtools": "0.8.0",

### 🛠️ To reproduce

private link

### 🌈 Expected behavior

expected to show the inspection tool then bring up Editor

**Comment by antfu** [comment] 2023-10-11 07:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-11 07:31 UTC
Labels: bug
