### ISSUE TITLE
fix: Pinia not installing correctly

### ISSUE THREAD

**Issue by AbrahimZaman360** [nuxt/devtools#486] opened 2023-10-20 12:52 UTC
### 🐛 The bug

On my system, @pinia/nuxt is installed but not @pinia.
It might be an error according to pinia docs, we also have to install @pinia to fix it in Devtools Installation.

### 🛠️ To reproduce

Installation of Pinia

### 🌈 Expected behavior

Should Install Correctly without giving any module error.

**Comment by arashsheyda** [comment] 2023-10-20 16:17
so when you run `[packageManager] install @pinia/nuxt` you get error? what error are you getting and why do you think it's related to devtools?

**Comment by AbrahimZaman360** [comment] 2023-10-20 18:30
Let's retry

**Comment by AbrahimZaman360** [comment] 2023-10-20 18:36
> so when you run `[packageManager] install @pinia/nuxt` you get error? what error are you getting and why do you think it's related to devtools?

![image](https://github.com/nuxt/devtools/assets/46282325/f2664f01-fd71-428c-ac52-3b209e3af0a2)

**Comment by AbrahimZaman360** [comment] 2023-10-20 18:36
Devtools are not installing the @pinia main package.

**Comment by arashsheyda** [comment] 2023-10-21 16:30
I don't think this is related to DevTools though, can you delete your `node_modules` and re-install dependencies, and if possible share a small reproduction so we can undrstand better, thanks

**Comment by antfu** [comment] 2023-10-21 18:19
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-21 18:19 UTC
Labels: bug

**Comment by AbrahimZaman360** [comment] 2023-10-22 04:14
No, it gives an error above ⬆️ when i install through devtools

**Comment by AbrahimZaman360** [comment] 2023-10-22 04:15
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
> Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Add @pinia package along with @pinia/nuxt.
Maybe
