### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by castrogarciajs** [nuxt/devtools#524] opened 2023-11-23 02:10 UTC
### 🐛 The bug

Nuxt Info: 

`- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, app, modules, css, swiper, pinia, ui, colorMode, postcss
- Runtime Modules:  @nuxt/ui@2.10.0, @nuxt/image@1.1.0, @pinia/nuxt@0.5.1, nuxt-swiper@1.2.2
- Build Modules:    -
`
![err](https://github.com/nuxt/devtools/assets/116913262/33f34456-91d1-48be-910d-fd4af7f3556a)

### 🛠️ To reproduce

.

### 🌈 Expected behavior

.

### ℹ️ Additional context

`<--- Last few GCs --->

[15184:000002795DB98DE0]  1903530 ms: Scavenge 1993.2 (2079.9) -> 1986.8 (2083.9) MB, 69.08 / 0.00 ms  (average mu = 0.293, current mu = 0.239) allocation failure;
[15184:000002795DB98DE0]  1904860 ms: Mark-Compact 2000.3 (2084.7) -> 1977.3 (2085.2) MB, 1218.88 / 0.00 ms  (average mu = 0.284, current mu = 0.275) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7599F433F node::SetCppgcReference+15695
 2: 00007FF75996EC26 EVP_MD_meth_get_input_blocksize+78566
 3: 00007FF759970A11 EVP_MD_meth_get_input_blocksize+86225
 4: 00007FF75A3DA7E1 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF75A3C3F78 v8::Function::Experimental_IsNopFunction+1336
 6: 00007FF75A2257E0 v8::Platform::SystemClockTimeMillis+659552
 7: 00007FF75A231A63 v8::Platform::SystemClockTimeMillis+709347
 8: 00007FF75A22F3C4 v8::Platform::SystemClockTimeMillis+699460
 9: 00007FF75A222500 v8::Platform::SystemClockTimeMillis+646528
10: 00007FF75A237B7A v8::Platform::SystemClockTimeMillis+734202
11: 00007FF75A2383F7 v8::Platform::SystemClockTimeMillis+736375
12: 00007FF75A246D1F v8::Platform::SystemClockTimeMillis+796063
13: 00007FF759F072E5 v8::CodeEvent::GetFunctionName+116773
14: 00007FF6FA45AAFA

 ERROR  [unhandledRejection] read ECONNRESET                    11:39:09 a. m.

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

 ERROR  [unhandledRejection] read ECONNRESET                    11:39:09 a. m.

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

 ERROR  [unhandledRejection] read ECONNRESET                    11:39:09 a. m.

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

 ERROR  [unhandledRejection] read ECONNRESET                    11:39:09 a. m.

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)`

**Comment by antfu** [comment] 2023-11-23 11:13
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-23 11:13 UTC
Labels: bug
