### ISSUE TITLE
devtools conflict with Nuxt 3.4.1 (and Pinia)

### ISSUE THREAD

**Issue by jordigasau** [nuxt/devtools#191] opened 2023-04-19 16:31 UTC
Hello, I have found an issue with devtools and pinia. I'm runing a fresh install of the latest version of Nuxt (3.4.1) on a new MacMini.

````
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: nuxt-app@undefined                                                                    6:28:19 PM
npm ERR! Found: vue@3.2.47
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.47" from @nuxt/vite-builder@3.4.1
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"3.4.1" from nuxt@3.4.1
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.4.1" from the root project
npm ERR!       1 more (@nuxt/devtools)
npm ERR!   peer vue@">=2.7 || >=3" from @unhead/vue@1.1.26
npm ERR!   node_modules/@unhead/vue
npm ERR!     @unhead/vue@"^1.1.25" from nuxt@3.4.1
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.4.1" from the root project
npm ERR!       1 more (@nuxt/devtools)
npm ERR!   5 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! pinia@"^2.0.34" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.34
npm ERR!     node_modules/pinia
npm ERR!       pinia@"^2.0.34" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

**Comment by antfu** [comment] 2023-04-19 18:42
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-04-19 18:42 UTC
