### ISSUE TITLE
Vite Error (Unquoted attribute value cannot contain U+0022)

### ISSUE THREAD

**Issue by casualmatt** [nuxt/devtools#107] opened 2023-03-05 17:22 UTC
I have faced this issue trying to install the devtool in nuxt as a module. 
Here is some info for context:

OS: Ubuntu 22.04
Node: v16.19.1
tested with local node install and in a dev container. 

Module installed on the project:
```
modules: [
    "@nuxtjs/tailwindcss",
    "nuxt-social-tags",
    "@nuxtjs/i18n",
    "nuxt-directus",
    "nuxt-headlessui",
    "@vueuse/nuxt",
    "@nuxt/devtools",
    //    "@nuxtjs/partytown",
  ],
```
dependencies:

```
"devDependencies": {
    "@nuxt/devtools": "^0.2.5",
    "@nuxtjs/i18n": "^8.0.0-beta.10",
    "@nuxtjs/partytown": "^1.3.0",
    "@nuxtjs/tailwindcss": "^6.4.0",
    "@tailwindcss/forms": "^0.5.3",
    "@vueuse/core": "^9.6.0",
    "@vueuse/nuxt": "^9.6.0",
    "nuxt": "^3.2.3",
    "nuxt-headlessui": "^1.1.1"
  },
  "dependencies": {
    "nuxt-directus": "^3.2.2",
    "nuxt-social-tags": "^1.2.3",
    "stripe": "^11.6.0"
  }
```

logs:

```
 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`).


 ERROR  Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (`). (repeated 3 times)

ℹ Vite client warmed up in 1824ms
✔ Nitro built in 172 ms
locale it-IT
[Vue warn]: Unhandled error during execution of setup function 
  at <LayoutLoader key="default" name="default" hasTransition=true >
[nuxt] error caught during app initialization [[vite-node] [plugin:vite-plugin-vue-inspector] [18] /components/corporate/navbar.vue?vue&type=i18n&index=0&lang.yaml <br><pre>export default function (Component) {
  Component.__i18n = Component.__i18n || []
  Component.__i18n.push({
    "locale": "",
    "resource": {
      "en-US": {
        "menu-path": {
          "smalti-universali": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/smalti-universali"])};fn.source="/brand/p/smalti-universali";return fn;})(),
          "fondi-protettivi": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/fondi-protettivi"])};fn.source="/brand/p/fondi-protettivi";return fn;})(),
          "trattamento-legno": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/trattamento-legno"])};fn.source="/brand/p/trattamento-legno";return fn;})()
        }
      },
      "it-IT": {
        "title": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["Questa è la Pagina di &lt;b data-v-inspector=\"components/corporate/navbar.vue:176:32\"&gt;brand&lt;/b&gt;"])};fn.source="Questa è la Pagina di &lt;b data-v-inspector=\"components/corporate/navbar.vue:176:32\"&gt;brand&lt;/b&gt;";return fn;})(),
        "seo": {
          "title": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["brand: ecosmalto per tutte le superfici"])};fn.source="brand: ecosmalto per tutte le superfici";return fn;})(),
          "description": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["Linea di ecosmalti per ogni superficie e supporto nata per sostenere la cultura del riciclo e del riuso contro gli sprechi."])};fn.source="Linea di ecosmalti per ogni superficie e supporto nata per sostenere la cultura del riciclo e del riuso contro gli sprechi.";return fn;})()
        }
      }
    }
  })
}</pre><br>
at /components/corporate/navbar.vue?vue&type=i18n&index=0&lang.yaml ] {
  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: 'Vite Error',
  __nuxt_error: true
}
locale it-IT
[Vue warn]: Unhandled error during execution of setup function 
  at <LayoutLoader key="default" name="default" hasTransition=true >
[nuxt] error caught during app initialization [[vite-node] [plugin:vite-plugin-vue-inspector] [18] /components/corporate/navbar.vue?vue&type=i18n&index=0&lang.yaml <br><pre>export default function (Component) {
  Component.__i18n = Component.__i18n || []
  Component.__i18n.push({
    "locale": "",
    "resource": {
      "en-US": {
        "menu-path": {
          "smalti-universali": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/smalti-universali"])};fn.source="/brand/p/smalti-universali";return fn;})(),
          "fondi-protettivi": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/fondi-protettivi"])};fn.source="/brand/p/fondi-protettivi";return fn;})(),
          "trattamento-legno": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["/brand/p/trattamento-legno"])};fn.source="/brand/p/trattamento-legno";return fn;})()
        }
      },
      "it-IT": {
        "title": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["Questa è la Pagina di &lt;b data-v-inspector=\"components/corporate/navbar.vue:176:32\"&gt;brand&lt;/b&gt;"])};fn.source="Questa è la Pagina di &lt;b data-v-inspector=\"components/corporate/navbar.vue:176:32\"&gt;brand&lt;/b&gt;";return fn;})(),
        "seo": {
          "title": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["brand: ecosmalto per tutte le superfici"])};fn.source="brand: ecosmalto per tutte le superfici";return fn;})(),
          "description": (()=&gt;{const fn=(ctx) =&gt; {const { normalize: _normalize } = ctx;return _normalize(["Linea di ecosmalti per ogni superficie e supporto nata per sostenere la cultura del riciclo e del riuso contro gli sprechi."])};fn.source="Linea di ecosmalti per ogni superficie e supporto nata per sostenere la cultura del riciclo e del riuso contro gli sprechi.";return fn;})()
        }
      }
    }
  })
}</pre><br>
at /components/corporate/navbar.vue?vue&type=i18n&index=0&lang.yaml ] {
  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: 'Vite Error',
  __nuxt_error: true
}
```

**Comment by antfu** [comment] 2023-03-06 01:39
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-06 01:39 UTC

**Comment by RokeAlvo** [comment] 2023-09-12 04:14
@casualmatt Hi, did you solve the problem?
