### ISSUE TITLE
WebSocket connection to 'ws://localhost:3000/__nuxt_devtools__/entry' failed

### ISSUE THREAD

**Issue by Dodobibi** [nuxt/devtools#144] opened 2023-03-20 12:30 UTC
Using devtools when another middleware websocket is registered won't work.

`WebSocket connection to 'ws://localhost:3000/__nuxt_devtools__/entry' failed:`

Maybe devtool can check url path, or registering only necessary path for filtering implementation ?

https://github.com/nuxt/devtools/blob/4deb883e190149dad3b1c5475b02d3db44edec6e/packages/devtools/src/server-rpc/index.ts#L83

**Comment by antfu** [comment] 2023-03-20 16:44
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-20 16:44 UTC

**Comment by peirix** [comment] 2023-03-29 14:06
Running into the same issue when I have another module that uses websockets.
Steps to reproduce:
Install nuxt,
Install nuxt-socket-io module
Install devtools module
Try running the project with both modules active.
