### ISSUE TITLE
help: Can not open Vue components in the editor

### ISSUE THREAD

**Issue by Archetipo95** [nuxt/devtools#325] opened 2023-07-13 09:28 UTC
### 📚 What are you trying to do?

I'm not sure if I'm doing something wrong but it's not working and it's giving me this error in the editor console when I try to open any component from the web page with the inspect.
`
Could not open Small.vue in the editor. 
The editor process exited with an error: spawn code ENOENT.
`

### 🔍 What have you tried?

Updating the lates versione of devtools (currently "@nuxt/devtools": "0.6.7")
Updating node to v16.20.0

### ℹ️ Additional context

I don't know if I have to install the VS code server, currently is not installed.
I don't know how to install VS code server on mac os.

**Comment by Archetipo95** [comment] 2023-07-23 20:01
So the minimal reproduction I was able to run was with `npx nuxi init <app>`
So there must be something wrong from my side. Can you help me to debug this problem? Maybe someone else will encounter it too.

**Comment by Archetipo95** [comment] 2023-07-23 20:08
Update:
I tried with node v18 and now the component selector is still not opening the component in vs code, but there is no error anymore about the `ENOENT`

**Comment by Jordan-TTC-Design** [comment] 2023-08-08 02:44
I have the same problem after change to apple chip mac....

**Comment by sunpm** [comment] 2023-08-13 02:14
I have the same problem with an intel chip mac

**Comment by antfu** [comment] 2023-10-11 07:32
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-11 07:32 UTC
Labels: help wanted
