### ISSUE TITLE
I am not able to run Nuxt Devtools

### ISSUE THREAD

**Issue by sarwangds** [nuxt/devtools#76] opened 2023-02-15 20:42 UTC
I created Nuxt project with version "3.2.0", and I installed nuxt devtools as mentioned on https://github.com/nuxt/devtools.

after that I restarted nuxt app, and tried to press Alt+D, nothing happens and nothing shows in the chrome dev tools

**Comment by alexzhang1030** [comment] 2023-02-16 07:55
Nuxt Devtools is a iframe embed into your page. Not at your chrome devtools. Just click the bottom icon after started Nuxt:

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/49969959/219302379-14e9a280-3919-4fb4-b15e-4fd72c7a61b2.png">

@sarwangds

**Comment by antfu** [comment] 2023-02-22 15:20
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-22 15:20 UTC

**Comment by sarwangds** [comment] 2023-02-22 15:46
@antfu well, I forgot to mention, it didn't work like that, I had to install it as Module and it worked just fine.
