### ISSUE TITLE
help: something is wrong after enable to devtools

### ISSUE THREAD

**Issue by greatelv** [nuxt/devtools#354] opened 2023-08-02 06:35 UTC
### 📚 What are you trying to do?

This message shown console and browser after installed devtools via npx.
Does anyone else have a similar problem?

[500] Package import specifier "#app" is not defined in package /Users/weolbu/.nvm/versions/node/v18.14.0/lib/node_modules/@nuxt/devtools/package.json imported from /Users/weolbu/.nvm/versions/node/v18.14.0/lib/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.mjs
  at new NodeError (node:internal/errors:399:5)  
  at importNotDefined (node:internal/modules/esm/resolve:350:10)  
  at packageImportsResolve (node:internal/modules/esm/resolve:777:9)  
  at moduleResolve (node:internal/modules/esm/resolve:932:16)  
  at defaultResolve (node:internal/modules/esm/resolve:1153:11)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
  at link (node:internal/modules/esm/module_job:76:36)

[ScreenShot]
<img width="1468" alt="image" src="https://github.com/nuxt/devtools/assets/3984956/3138c340-a556-408f-a2e8-e88bd93b6e6e">

**Comment by greatelv** [comment] 2023-08-02 06:35
For your information, it works well if I disable it.

**Comment by antfu** [comment] 2023-08-02 09:42
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by antfu** [comment] 2023-10-15 19:52
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-15 19:52 UTC
Labels: help wanted
