### ISSUE TITLE
fix: histoire

### ISSUE THREAD

**Issue by francisashley** [nuxt/devtools#475] opened 2023-10-17 08:44 UTC
### 🐛 The bug

When `@nuxt/devtools` is included in `nuxt.config.js`, like:

```
export default defineNuxtConfig({
  modules: ["@nuxt/devtools"],
});
```

Running `histoire` in dev mode will start nuxt but then crash pretty quickly with:

<img width="1074" alt="Screenshot 2023-10-17 at 09 38 05" src="https://github.com/nuxt/devtools/assets/12685308/020796a5-549d-4103-8ed5-b934963239d9">

Removing the devtools module, allows histoire to run fine.

### 🛠️ To reproduce

 https://stackblitz.com/edit/nuxt-starter-qar953

Please run `npm install && npm run story:dev` in the stackblitz terminal to reproduce.

### 🌈 Expected behavior

For histoire to run fine when `nuxt/devtools` has been loaded as a module in nuxt.config.ts.

**Comment by antfu** [comment] 2023-10-17 09:15
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by francisashley** [comment] 2023-10-17 23:24
@antfu fair point. I have created a stackblitz example with a reproduction of the issue. https://stackblitz.com/edit/nuxt-starter-qar953. Please run `npm install && npm run story:dev` in the terminal to see `ReferenceError [Error]: localStorage is not defined` will throw in the terminal. This issue disappears when removing `modules: ['@nuxt/devtools']` from `nuxt.config.ts`.

**Comment by francisashley** [comment] 2023-10-22 12:33
Here is a video of the issue:


https://github.com/nuxt/devtools/assets/12685308/a1a03dbb-5687-4d7f-a77f-4f9f64caf1cc


1. I show `nuxt.config.ts` and highlight some unrelated config that was added to address another bug blocking histoire booting, i believe this has already been patched in next version - https://github.com/nuxt/nuxt/issues/23826, https://github.com/histoire-dev/histoire/commit/05bcd28cd5d13012e2bdb9ae93f2a0f6d69e1ef5.
2. I `npm install && npm run dev` run which boots fine.
3. I rerun with `npm install && npm run story:dev` which shows the bug in this ticket.
4. I show the contents of `histoire.config.ts` and the test story files.

**Comment by francisashley** [comment] 2023-10-22 13:04
https://github.com/nuxt/nuxt/issues/23863#issuecomment-1774086517 explains this is being fixed here https://github.com/histoire-dev/histoire/pull/611.

**Closed** 2023-11-20 13:28 UTC
Labels: bug
