### ISSUE TITLE
[unhandledRejection] Cannot read properties of undefined (reading 'content')                                                                                                                                                       

### ISSUE THREAD

**Issue by L422Y** [nuxt/devtools#44] opened 2023-02-09 21:17 UTC
System: macOS Ventura, MacBook Pro M1 Max

Nuxi 3.2.0
Nuxt 3.2.0 with Nitro 2.2.1

Code:
```js
const contentVer = require$$8['cache-version'].content;
```
Error:
```
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'content')                                                                                                                                                       15:59:24

  at /Users/larry/.nvm/versions/node/v18.8.0/lib/node_modules/@nuxt/devtools/dist/chunks/index.mjs:11113:48
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
  at async checkForUpdateOf (/Users/larry/.nvm/versions/node/v18.8.0/lib/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8166:21)
  at async Promise.all (index 0)
  at async checkForUpdates (/Users/larry/.nvm/versions/node/v18.8.0/lib/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8184:19)

```

**Comment by ngajhede** [comment] 2023-02-09 22:09
duplicate of #41

**Closed** 2023-02-11 19:43 UTC
