### ISSUE TITLE
Black empty Box

### ISSUE THREAD

**Issue by zswilhelm** [nuxt/devtools#48] opened 2023-02-10 08:59 UTC
npm run dev
✔ Nuxt Devtools is enabled v0.1.0 (experimental)       

when i open the page on browser, 
i see the icon button, click it, 
but only black empty box is visable

node v19.5.0
Nuxt 3.2.0 with Nitro 2.2.1  

  "devDependencies": {
    "@nuxt/devtools": "npm:@nuxt/devtools-edge@latest"
}

chrome Version 110.0.5481.77

**Comment by zswilhelm** [comment] 2023-02-10 09:23
console.log:
rpc.65a41b65.js:1 WebSocket connection to 'ws://localhost:3000/__nuxt_devtools__/entry' failed: 
N @ rpc.65a41b65.js:1
(anonymous) @ rpc.65a41b65.js:1
rpc.65a41b65.js:1 [nuxt-devtools] WebSocket closed, reconnecting...
rpc.65a41b65.js:1 Uncaught (in promise) ReferenceError: Cannot access 'L' before initialization
    at rpc.65a41b65.js:1:2401

**Comment by antfu** [comment] 2023-02-10 09:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-02-10 09:23 UTC

**Comment by adamja** [comment] 2024-01-03 03:55
I just had this issue with my nuxt dev server. The reason my dev tools was all black was because I was going through a proxy and i didn't have websocketsupport enabled. The dev tools I assume uses a different port to the actual web page and therefore shows all black when that port is blocked...

Good luck :)

---

I am using nginx proxy manager...
![image](https://github.com/nuxt/devtools/assets/22337050/aa61f8ca-6513-4b4a-a419-5b9c1ddc70e9)

**Comment by AlexDigital974** [comment] 2024-12-17 14:27
@zswilhelm  if this can help you i had the exact same issue and to add more context , its not link to chrome  , ALL browsers show the devtool icon but the iframe is always blank.
I look as the websocket ws error and i added this to `nuxt.config.ts` , which fix my debtools

 `vite: { server: { hmr: { protocol: 'http', host: 'localhost', clientPort: 3000, port: 3000, }, }, }`

Why do i need to specially add this ? no idea . i install nuxt 3.9.2 at the time of writing with
pnpm dlx nuxi@latest init <project-name> and the devtool for me is blank of all browser by default until i add this vite setting

and no i dont have proxy or any weird thing
