### ISSUE TITLE
help: Devtools WebSocket disconnected

### ISSUE THREAD

**Issue by 048616** [nuxt/devtools#596] opened 2024-02-08 13:54 UTC
### 📚 What are you trying to do?

Hi, I'm trying to use devtools Nux 3 project which extend a layer but it does't work propely.
DevTools works but it shows Connecting to server... for a few time then the message turn in "WebSocket disconnected".
![devtool](https://github.com/nuxt/devtools/assets/38950617/562e3874-7f5c-4856-b2a8-617a24d95b2e)

### 🔍 What have you tried?

I've spent a lot of time trying to solve it, I'he read all documentation avaiable online.
here my last configuration:
devtools: {
    enabled: true,
    },
  extends: ['../core-layer'],
  devServer: {
    host: '0.0.0.0',
    port: 80,
  },

**Comment by antfu** [comment] 2024-03-05 11:06
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-05 11:06 UTC
Labels: help wanted
