### ISSUE TITLE
presetIcons config break unocss

### ISSUE THREAD

**Issue by ManUtopiK** [nuxt/devtools#146] opened 2023-03-20 16:40 UTC
Importing devtools-ui-kit in my project break uncoss :
`Internal server error: Cannot read properties of undefined (reading '') `
It points to that line : https://github.com/nuxt/devtools/blob/4deb883e190149dad3b1c5475b02d3db44edec6e/packages/devtools-ui-kit/src/unocss.ts#L142

**Comment by antfu** [comment] 2023-03-20 16:43
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-20 16:43 UTC
